// ─────────────────────────────────────────
//  services/zipper.js
//  Builds ZIP from crawled pages + assets
// ─────────────────────────────────────────
const archiver = require('archiver');
const { PassThrough } = require('stream');
const path = require('path');
const { urlToLocalPath } = require('./downloader');

class ZipperService {
  constructor({ jobId, minify, brokenLinks, originalUrl }) {
    this.jobId       = jobId;
    this.minify      = minify;
    this.brokenLinks = brokenLinks;
    this.originalUrl = originalUrl;
  }

  /**
   * Builds a ZIP buffer from pages (HTML) + assets (binary files).
   * Returns a Buffer.
   */
  build(pages, assets) {
    return new Promise((resolve, reject) => {
      const chunks = [];
      const passThrough = new PassThrough();
      passThrough.on('data', (chunk) => chunks.push(chunk));
      passThrough.on('end', () => resolve(Buffer.concat(chunks)));
      passThrough.on('error', reject);

      const archive = archiver('zip', { zlib: { level: 6 } });
      archive.on('error', reject);
      archive.pipe(passThrough);

      // ── HTML pages ───────────────────────────
      const seenPaths = new Set();
      for (const { url, html } of pages) {
        let localPath = urlToLocalPath(url, new URL(url).hostname);
        if (seenPaths.has(localPath)) continue;
        seenPaths.add(localPath);

        const content = this.minify ? minifyHtml(html) : html;
        archive.append(Buffer.from(content, 'utf8'), { name: localPath });
      }

      // ── Binary assets ────────────────────────
      for (const { localPath, buffer, url } of assets) {
        if (seenPaths.has(localPath)) continue;
        seenPaths.add(localPath);

        let finalBuffer = buffer;
        if (this.minify) {
          if (localPath.endsWith('.css'))  finalBuffer = Buffer.from(minifyCss(buffer.toString('utf8')), 'utf8');
          if (localPath.endsWith('.js'))   finalBuffer = Buffer.from(minifyJs(buffer.toString('utf8')), 'utf8');
        }
        archive.append(finalBuffer, { name: localPath });
      }

      // ── _sitegrab/ meta folder ───────────────
      archive.append(this._buildReadme(pages, assets), { name: '_sitegrab/README.md' });
      archive.append(this._buildManifest(pages, assets), { name: '_sitegrab/manifest.json' });
      archive.append(this._buildBrokenLinks(), { name: '_sitegrab/broken-links.txt' });

      archive.finalize();
    });
  }

  _buildReadme(pages, assets) {
    const hostname = new URL(this.originalUrl).hostname;
    const totalMb  = (assets.reduce((s, a) => s + a.buffer.length, 0) / 1024 / 1024).toFixed(2);
    return Buffer.from([
      `# SiteGrab Pro — Capture Report`,
      ``,
      `**Source URL:** ${this.originalUrl}`,
      `**Captured:** ${new Date().toUTCString()}`,
      ``,
      `## Stats`,
      `- Pages crawled: ${pages.length}`,
      `- Assets downloaded: ${assets.length}`,
      `- Broken/skipped: ${this.brokenLinks.length}`,
      `- Total size: ~${totalMb} MB`,
      ``,
      `## Contents`,
      `All files mirror the original folder structure from **${hostname}**.`,
      ``,
      `## Offline Compatibility`,
      `Simple HTML/CSS sites work offline at ~95%. React/SPA apps may need`,
      `their build step rerun. API-dependent content will not load offline.`,
      ``,
      `## Not Captured`,
      `- Streamed video (HLS/DASH)`,
      `- Auth-protected resources`,
      `- Cloudflare-blocked assets`,
      `- Runtime/procedural GPU content`,
      ``,
      `Generated by SiteGrab Pro v1.0`,
    ].join('\n'), 'utf8');
  }

  _buildManifest(pages, assets) {
    const manifest = {
      generatedAt: new Date().toISOString(),
      sourceUrl: this.originalUrl,
      pages: pages.map((p) => ({ url: p.url, localPath: urlToLocalPath(p.url, new URL(p.url).hostname) })),
      assets: assets.map((a) => ({ url: a.url, localPath: a.localPath, sizeBytes: a.buffer.length })),
    };
    return Buffer.from(JSON.stringify(manifest, null, 2), 'utf8');
  }

  _buildBrokenLinks() {
    if (!this.brokenLinks.length) return Buffer.from('No broken links found.\n', 'utf8');
    const lines = this.brokenLinks.map((b) => `${b.url}  →  ${b.reason}`);
    return Buffer.from(['# Broken / Skipped Links', '', ...lines].join('\n'), 'utf8');
  }
}

// ── Lightweight minifiers (no external deps) ──────────────────
function minifyHtml(html) {
  return html
    .replace(/<!--[\s\S]*?-->/g, '')   // remove comments
    .replace(/\s{2,}/g, ' ')           // collapse whitespace
    .replace(/>\s+</g, '><')           // remove whitespace between tags
    .trim();
}

function minifyCss(css) {
  return css
    .replace(/\/\*[\s\S]*?\*\//g, '')  // remove comments
    .replace(/\s{2,}/g, ' ')
    .replace(/\s*([{}:;,>~+])\s*/g, '$1')
    .trim();
}

function minifyJs(js) {
  // Minimal — strips single-line comments and extra blank lines
  return js
    .replace(/\/\/[^\n]*/g, '')
    .replace(/\n{2,}/g, '\n')
    .trim();
}

module.exports = ZipperService;
